{{- if .Values.ingress.aws }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name : blue-green-ingress
  namespace: blue-green-rollout
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    # alb.ingress.kubernetes.io/group.order: '1'
    # alb.ingress.kubernetes.io/group.name: myapp
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    # alb.ingress.kubernetes.io/ssl-redirect: '443'
    # alb.ingress.kubernetes.io/certificate-arn: ""
spec:
  ingressClassName: alb
  rules:
###### bluegreen.live.com will be a enduser facing web URL #######
  - host: "*.amazonaws.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: active-svc
            port:
              number: 80
###### bluegreen.staging.com will be internal testing web URL (Like for new app version fucntionality for QA testers) ######
  - host: "*.amazonaws.com"
    http:
      paths:
      - path: /staging
        pathType: Prefix
        backend:
          service:
            name: preview-svc
            port:
              number: 80
{{- end }}

---
{{- if .Values.ingress.onprem }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name : blue-green-ingress
  namespace: blue-green-rollout
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
###### bluegreen.live.com will be a enduser facing web URL #######
  - host: bluegreen.live.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: active-svc
            port:
              number: 80
###### bluegreen.staging.com will be internal testing web URL (Like for new app version fucntionality for QA testers) ######
  - host: bluegreen.staging.com
    http:
      paths:
      - path: /staging
        pathType: Prefix
        backend:
          service:
            name: preview-svc
            port:
              number: 80
{{- end }}
