apiVersion: v1
kind: Service
metadata:
  name: active-svc
  namespace: blue-green-rollout
spec:
  ports:
  - port: 80 #service port  #kubeproxy will open port on worker node to which can route traffic to alb
    targetPort: 8080 #container port
    protocol: TCP
  type: NodePort
  selector:
    app: testing
---
apiVersion: v1
kind: Service
metadata:
  name: preview-svc
  namespace: blue-green-rollout
spec:
  ports:
  - port: 80 #service port  #kubeproxy will open port on worker node to which can route traffic to alb
    targetPort: 8080 #container port
    protocol: TCP
  type: NodePort
  selector:
    app: testing
