apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: as-infra
  labels:
    app.kubernetes.io/managed-by: Helm  
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  project: default
  source:
    repoURL: https://github.com/prati08/EKS-ArgoCD-Terraform.git
    path: EKS-ArgoCD-Terraform-Gitops/deployments/charts/argo-rollouts/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: as-infra
  syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
