apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: as-infra
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  source:
    repoURL: https://github.com/prati08/EKS-ArgoCD-Terraform.git
    path: EKS-ArgoCD-Terraform-Gitops/deployments/charts/argo-cd/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: as-infra
  syncPolicy:
    syncOptions:
        - CreateNamespace=false
    automated:
      selfHeal: true
      prune: false
