apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: as-infra
  labels:
    app.kubernetes.io/managed-by: Helm  
  annotations:
    argocd.argoproj.io/hook: Presync
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/prati08/EKS-ArgoCD-Terraform.git
    path: EKS-ArgoCD-Terraform-Gitops/deployments/charts/argo-rollouts/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

{{- if .Values.rootApp.noSyncPolicy }}
  syncPolicy: null
{{- else if .Values.rootApp.defaultPolicy }}
  syncPolicy: {{ toJson .Values.automatedDefaultSyncPolicy }}
{{- else if .Values.rootApp.customPolicy }}
  syncPolicy: {{ toJson .Values.automatedCustomSyncPolicy }}
{{- end }}
