apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: as-infra
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  project: default
  source:
    repoURL: https://github.com/prati08/EKS-ArgoCD-Terraform.git
    path: EKS-ArgoCD-Terraform-Gitops/deployments/charts/root-app/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
