apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-app-cluster-1
  namespace: as-infra
  labels:
    app.kubernetes.io/managed-by: Helm  
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/prati08/EKS-ArgoCD-Terraform.git 
    path: EKS-ArgoCD-Terraform-Gitops/single_cluster/01-staging/charts/staging
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
        - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
