apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-app-cluster-1
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:prati08/EKS-ArgoCD-Terraform.git
    path: EKS-ArgoCD-Terraform-Gitops/single_cluster/01-staging/charts/staging
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: staging-app-cluster-1

{{- if .Values.rootApp.noSyncPolicy }}
  syncPolicy: null
{{- else if .Values.rootApp.defaultPolicy }}
  syncPolicy: {{ toJson .Values.automatedDefaultSyncPolicy }}
{{- else if .Values.rootApp.customPolicy }}
  syncPolicy: {{ toJson .Values.automatedCustomSyncPolicy }}
{{- end }}
