apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-blue-green-rollout-app
  namespace: as-infra
  labels:
    app.kubernetes.io/managed-by: Helm
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/prati08/EKS-ArgoCD-Terraform.git
    path: EKS-ArgoCD-Terraform-Gitops-Service/deployments/charts/staging/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
        - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
