apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-blue-green-rollout-app
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:prati08/EKS-ArgoCD-Terraform.git
    path: EKS-ArgoCD-Terraform-Gitops-Service/deployments/charts/staging/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

{{- if .Values.stageBlueGreenApp.noSyncPolicy }}
  syncPolicy: null
{{- else if .Values.stageBlueGreenApp.defaultPolicy }}
  syncPolicy: {{ toJson .Values.automatedDefaultSyncPolicy }}
{{- else if .Values.stageBlueGreenApp.customPolicy }}
  syncPolicy: {{ toJson .Values.automatedCustomSyncPolicy }}
{{- end }}
